ARG golang_image
FROM ${golang_image}

ADD .   /go/src/github.com/goharbor/harbor-scanner-trivy/
WORKDIR /go/src/github.com/goharbor/harbor-scanner-trivy/

ARG TARGETARCHS
RUN set -eux; \
    for targetarch in ${TARGETARCHS}; do \
        GOOS=linux GOARCH=${targetarch} GO111MODULE=on CGO_ENABLED=0 go build -a -o scanner-trivy-linux-${targetarch} cmd/scanner-trivy/main.go; \
    done
